name: InfinityBucket
version: '1.0'
main: de.morice.infinitybucket.InfinityBucket
api-version: 1.19
authors: [ morice ]
description: Adds Infinite Buckets to the game

commands:
  givebucket:
    description: "Gives the player a bucket"